Tuya Fan Support
athombv/com.tuya pull request #14
Opened 2024-06-08 04:57 UTC by gslender

This adds Fan device/driver support for the Tuya App

2024-06-09 13:46 UTC, WeeJeWel requested changes
WOW! Now this is how I like PRs! 😍 

I only have added two small remarks. Could you solve those? Then we'll merge & publish this PR.

Again, thank you!!

2024-06-09 13:46 UTC, WeeJeWel commented on lib/TuyaOAuth2DriverFan.js
> +class TuyaOAuth2DriverLight extends TuyaOAuth2Driver {
Can you rename this to `TuyaOAuth2DriverFan`?

2024-06-09 13:46 UTC, WeeJeWel commented on drivers/fan/pair/select_country.html
> +<style type="text/css">
This file is not used anymore. Can you remove it?

2024-06-09 21:56 UTC, gslender commented
Changes made and should be ready to be accepted

2024-06-10 10:15 UTC, WeeJeWel commented
Amazing, thank you!

2024-06-10 10:15 UTC, merged