Add heater of Large Home Appliances
athombv/com.tuya pull request #152
Opened 2024-08-15 09:34 UTC by bogguard

Adds support to include small and large heater instance.

Device and Specification : 

<details>

```json
 {
  "device": {
    "active_time": 1688287178,
    "biz_type": 18,
    "category": "rs",
    "create_time": 1688285375,
    "icon": "smart/icon/ay1513418289516FAXSV/df2cf842ab71c359308c3814492d5ee9.png",
    "id": "bfff3ce552aa537acbjj39",
    "ip": "<redacted>",
    "lat": "<redacted>",
    "local_key": "<redacted>",
    "lon": "<redacted>",
    "model": "RCDF211344",
    "name": "Weau pool heat pump",
    "online": true,
    "owner_id": "<redacted>",
    "product_id": "zqwet1zcvj2wcxzw",
    "product_name": "Weau pool heat pump",
    "status": [{
      "code": "switch",
      "value": true
    }, {
      "code": "mode",
      "value": "eheat"
    }, {
      "code": "temp_set",
      "value": 28
    }, {
      "code": "temp_current",
      "value": 253
    }, {
      "code": "fault",
      "value": 4
    }],
    "sub": false,
    "time_zone": "+02:00",
    "uid": "<redacted>",
    "update_time": 1723574253,
    "uuid": "<redacted>"
  },
  "specifications": {
    "category": "rs",
    "functions": [{
      "code": "switch",
      "desc": "{}",
      "name": "开关",
      "type": "Boolean",
      "values": "{}"
    }, {
      "code": "mode",
      "desc": "{\"range\":[\"auto\"]}",
      "name": "模式",
      "type": "Enum",
      "values": "{\"range\":[\"auto\"]}"
    }, {
      "code": "temp_set",
      "desc": "{\"unit\":\"℃\",\"min\":-500,\"max\":1000,\"scale\":0,\"step\":1}",
      "name": "温度设置",
      "type": "Integer",
      "values": "{\"unit\":\"℃\",\"min\":-500,\"max\":1000,\"scale\":0,\"step\":1}"
    }],
    "status": [{
      "code": "switch",
      "name": "开关",
      "type": "Boolean",
      "values": "{}"
    }, {
      "code": "mode",
      "name": "模式",
      "type": "Enum",
      "values": "{\"range\":[\"auto\"]}"
    }, {
      "code": "temp_set",
      "name": "温度设置",
      "type": "Integer",
      "values": "{\"unit\":\"℃\",\"min\":-500,\"max\":1000,\"scale\":0,\"step\":1}"
    }, {
      "code": "temp_current",
      "name": "当前温度",
      "type": "Integer",
      "values": "{\"unit\":\"℃\",\"min\":-1000,\"max\":1000,\"scale\":1,\"step\":1}"
    }, {
      "code": "fault",
      "name": "故障告警",
      "type": "bitmap",
      "values": "{\"label\":[\"sys_high_fault\",\"sys_low_fault\",\"flow_fault\",\"power_fault\",\"cooling_fault\",\"heating_fault\",\"temp_dif_fault\",\"in_temp_fault\",\"eff_temp_fault\",\"coil_temp_fault\",\"ret_temp_fault\",\"news_fault\",\"amb_temp_fault\",\"lack_water\",\"serious_fault\",\"sensor_fault\",\"motor_fault\"],\"maxlen\":16}"
    }]
  }
}
```

</details>

2024-08-15 09:37 UTC, bogguard commented
fyi, I tweaked the divide by 10 for the current temperature based on the max of the target_temperature. If it's above 100, I expect the value to be dived by 10.
This does expect that a heater value isn't going above 100 degrees, which should be fine based on the Tuya docs.

2024-08-15 14:53 UTC, bobvandevijver requested changes

2024-08-15 14:53 UTC, bobvandevijver commented on drivers/heater/device.ts
> +    if (this.hasCapability('lock')) {
This condition will never be true, as it checks the Homey capability. You will need to check for the Tuya capability instead.

2024-08-15 14:53 UTC, bobvandevijver commented on drivers/heater/device.ts
> +      }
You can remove this from the PR: we are going to add a setting for temperature scaling, which will be automatically set based on the scale from the device specification.

2024-08-15 19:43 UTC, bogguard commented on drivers/heater/device.ts
> +    if (this.hasCapability('lock')) {
Updated to hasTuyaCapability

2024-08-15 19:44 UTC, bogguard commented on drivers/heater/device.ts
> +      }
ok, leaving it out so currently current temp might have the wrong dimension

2024-08-16 07:47 UTC, bobvandevijver requested changes
Great work, just the bitmap one left! I do also like to remove the mode completely for now.

2024-08-16 07:47 UTC, bobvandevijver commented on app.json
> +    },
```suggestion
```

2024-08-16 07:47 UTC, bobvandevijver commented on drivers/heater/TuyaHeaterConstants.ts
> +  fault: 'fault' /* large appliances */,
```suggestion
  /* Large and small appliances */
  switch: 'onoff',
  temp_set: 'target_temperature',
  temp_current: 'measure_temperature',

  /* small appliances */
  lock: 'child_lock',
  work_power: 'measure_power',
  mode_eco: 'eco_mode',

  /* large appliances */
  child_lock: 'child_lock',
  eco: 'eco_mode',
  fault: 'fault',
```

2024-08-16 07:47 UTC, bobvandevijver commented on drivers/heater/device.ts
> +    }*/
```suggestion
```

2024-08-16 07:47 UTC, bobvandevijver commented on drivers/heater/device.ts
> +    }*/
```suggestion
```

2024-08-16 07:47 UTC, bobvandevijver commented on drivers/heater/driver.ts
> +    }
```suggestion
```

2024-08-16 07:47 UTC, bobvandevijver commented on drivers/heater/device.ts
> +      );
According to the specification the fault capability is a bitmap, which means that `status['fault'] - 1` would be wrong. See https://support.tuya.com/en/help/_detail/K9mc4euc6tq9i: every bit encodes one of the possible fault states. If the fault state would be zero (meaning all okay) you would be accessing value -1 of the label array which is an hard error.

2024-08-16 07:47 UTC, bobvandevijver commented on .homeycompose/capabilities/mode.json
> +}
```suggestion
```

Remove the whole file.

2024-08-16 07:47 UTC, bobvandevijver commented on .homeycompose/capabilities/fault.json
> +  "getable": true,
```suggestion
  "getable": true,
  "setable": false,
```

2024-08-16 07:47 UTC, bobvandevijver commented on app.json
> +      "getable": true,
```suggestion
      "getable": true,
      "setable": false,
```

2024-08-16 08:14 UTC, bogguard commented on drivers/heater/device.ts
> +      );
Thanks for the reference to the documentation. I wasn't aware multiple fault states could occur.
Rewrote the code to read out the bits and refer to the array for every fault state.

2024-08-16 09:01 UTC, bobvandevijver commented
@bogguard Looks you made a mistake with the rebase, can you solve that?

2024-08-16 10:15 UTC, bogguard commented
@bobvandevijver , cleaned up the current PR.
Takes into account your remarks and fixed the bitmap.

2024-08-16 10:45 UTC, JELoohuis requested changes
Looks good overall! Just some feedback on storing the fault labels.

2024-08-16 10:45 UTC, JELoohuis commented on drivers/heater/device.ts
> +      const faultOptions = this.getCapabilityOptions('fault').values;
While it shouldn't matter for functionality, it may be nicer to keep these values in the store, alongside the other Tuya configuration values.

2024-08-16 10:45 UTC, JELoohuis commented on drivers/heater/driver.ts
> +      }
Some devices have turned out to return empty specifications. Since this would result in undefined labels it would be nice to have a fallback value based on the documentation.

2024-08-16 11:45 UTC, bogguard commented on drivers/heater/driver.ts
> +      }
Added fallback with default heater fault values.

2024-08-16 11:48 UTC, bogguard commented on drivers/heater/device.ts
> +      const faultOptions = this.getCapabilityOptions('fault').values;
not exactly sure how you would like it to be. 
Adding tuya_capabilitie_options to the store and add it as functionality to the TuyaOAuth2Device?

2024-08-16 11:58 UTC, JELoohuis commented on drivers/heater/device.ts
> +      const faultOptions = this.getCapabilityOptions('fault').values;
You could add them as `props.store.tuya_fault_labels` during the pairing, and then access them in the device using `this.store.tuya_fault_labels` or `this.getStoreValue('tuya_fault_labels')`. Since this is only used here a method is probably overkill, though you could add it to just the heater device.

2024-08-17 13:02 UTC, bogguard commented on drivers/heater/device.ts
> +      const faultOptions = this.getCapabilityOptions('fault').values;
Fixed

2024-08-17 13:04 UTC, bogguard commented
@JELoohuis , tweaked the fault labels so they are now within the store and have a default fallback value when no specification is available

2024-08-19 07:29 UTC, bobvandevijver approved these changes
@bogguard Great work and thank you for making all requested updates each time! I do hope our comments on the PR weren't frustrating you too much (I know I might have become frustrated), but I do know that you can now say you have made a great contribution to this app 👍🏻

2024-08-19 07:30 UTC, merged