Add wireless switch
athombv/com.tuya pull request #242
Opened 2024-09-18 14:08 UTC by JELoohuis

-**Added support for wireless switches**
  Added support for 'wxkg' Tuya devices.
  The following capabilities were implemented:
  - battery_percentage (measure_battery)

  Additionally the following capabilities were implemented only in flows:
  - knob_switch_mode_1
  - switch_modeX, where X can be any value used to denote the sub-switch

2024-09-19 08:26 UTC, bobvandevijver requested changes

2024-09-19 08:26 UTC, bobvandevijver commented on drivers/button/driver.flow.compose.json
> +  "actions": [
Lets remove the actions

2024-09-19 12:41 UTC, bobvandevijver commented on drivers/button/driver.compose.json
> +  "capabilities": []
```suggestion
  "capabilities": ["measure_battery"]
```

2024-09-19 12:52 UTC, merged

2024-09-19 16:16 UTC, deejayreissue commented
Amazing, any ideas when there will be a test version to check out with the new device type please?

2024-09-20 08:32 UTC, bobvandevijver commented
@deejayreissue You can subscribe to the releases to receive a notification when a new test release is made. We hope to create a release as soon as possible, but we are currently waiting for a couple of blocking assets.