Expand sockets
athombv/com.tuya pull request #34
Opened 2024-06-28 15:24 UTC by JELoohuis

- **Added power/voltage/current measurement capabilities to sockets**
    [The documentation says the power output does not need to be scaled](https://developer.tuya.com/en/docs/iot/switch-socket-and-power-strip?id=K9gf7o5prgf7s#title-1-Support%20reporting%20commands%20to%20the%20cloud%20only), but my test devices scaled by a factor 10, so this documentation is likely incorrect.

- **Changed the onoff capability to toggle all switches on a socket on/off at once**
    This is a breaking change for people already testing the app with their sockets.
    Next to providing the obvious extra functionality, this prevents having to work around the default onoff flows for devices with multiple switches.

- **Added trigger/condition/action flow cards for individual switches on a socket**
    I opted for an autocomplete argument so the available sockets can be updated programmatically without many duplicate flow definitions.

2024-07-02 09:05 UTC, WeeJeWel requested changes

2024-07-02 09:05 UTC, WeeJeWel commented on .homeycompose/flow/conditions/sub_switch_is_on.json
> +{
Please use `driver.flow.compose.json` with the `"$filter": "capabilities=...` property.

2024-07-02 09:05 UTC, WeeJeWel commented on .homeycompose/flow/conditions/sub_switch_is_on.json
> +    "en": "A specific switch on the device is turned !{{on|off}}."
Hints don't show on/off I think...

2024-07-02 09:05 UTC, WeeJeWel commented on lib/TuyaOAuth2DriverSocket.js
> +    const switchCount = props.store.tuya_switches.length;
Please revert to the simple, hardcoded variant, which is much easier to read than this.

2024-07-02 12:15 UTC, JELoohuis commented on .homeycompose/flow/conditions/sub_switch_is_on.json
> +    "en": "A specific switch on the device is turned !{{on|off}}."
Whoops, missed that one in testing. It is removed in e99c4b7db83ffa9ff3113d5d564bf2b18ac6df3c

2024-07-02 12:16 UTC, JELoohuis commented on .homeycompose/flow/conditions/sub_switch_is_on.json
> +{
The flows have been made driver specific in e99c4b7db83ffa9ff3113d5d564bf2b18ac6df3c

2024-07-02 12:18 UTC, JELoohuis commented on lib/TuyaOAuth2DriverSocket.js
> +    const switchCount = props.store.tuya_switches.length;
I have unrolled the for-loop and restructured the handling of the onoff capability in fae207850bdcd147ecd83119ea6db69fbf30431f

2024-07-03 11:18 UTC, WeeJeWel requested changes

2024-07-03 11:18 UTC, WeeJeWel commented on drivers/socket/driver.flow.compose.json
> +      "$filter": "capabilities=onoff.switch_1|onoff.switch_2|onoff.switch_3|onoff.switch_4|onoff.switch_5|onoff.switch_6",
Please create a separate Flow card for every sub-switch. Dropdowns are too techy for this end.

2024-07-03 11:18 UTC, WeeJeWel commented on lib/TuyaOAuth2DeviceSocket.js
> +      this.registerCapabilityListener('onoff', (value) => this.allOnOff(value));
Use naming convention `onCapabilityOnoff`.

2024-07-03 11:18 UTC, WeeJeWel commented on lib/TuyaOAuth2DeviceSocket.js
> +        this.safeSetCapabilityValue(switchCapability, switchStatus).catch(this.error);
Just wrap `hasCapability` here for simplicity instead of `safeSetCapabilityValue`.

2024-07-03 11:18 UTC, WeeJeWel commented on lib/TuyaOAuth2DeviceSocket.js
> +        this.safeSetCapabilityValue(switchCapability, switchStatus).catch(this.error);
Worst case it rejects anyway.

2024-07-03 11:49 UTC, MerelHudepohl commented on drivers/socket/driver.flow.compose.json
> +      "$filter": "capabilities=onoff.switch_1|onoff.switch_2|onoff.switch_3|onoff.switch_4|onoff.switch_5|onoff.switch_6",
I disagree, if you use one flow card for each option it makes the Flow card overview cluttered. It is also not in line what we do with other apps. Plus editing a Flow is much easier if you can just edit the dropdown instead of selecting a whole new Flow card. 

![Screenshot 2024-07-03 at 13 46 26](https://github.com/athombv/com.tuya/assets/59914354/c4c01eca-5684-4804-b196-2336ae5eed51)

![Screenshot 2024-07-03 at 13 48 28](https://github.com/athombv/com.tuya/assets/59914354/9198d47a-3baa-40f8-b7e4-2854f4402b3d)

2024-07-08 08:40 UTC, WeeJeWel commented on drivers/socket/driver.flow.compose.json
> +      "$filter": "capabilities=onoff.switch_1|onoff.switch_2|onoff.switch_3|onoff.switch_4|onoff.switch_5|onoff.switch_6",
I'm sorry, but an `autocomplete` is meant for dynamic search queries, e.g. a Spotify track, not for pre-known values such as these.

Plus, it's more consistent with the 'Turn on' card.

2024-07-08 09:28 UTC, MerelHudepohl commented on drivers/socket/driver.flow.compose.json
> +      "$filter": "capabilities=onoff.switch_1|onoff.switch_2|onoff.switch_3|onoff.switch_4|onoff.switch_5|onoff.switch_6",
How about changing it to a `dropdown` argument instead of `autocomplete`?

2024-07-08 09:33 UTC, WeeJeWel commented on drivers/socket/driver.flow.compose.json
> +      "$filter": "capabilities=onoff.switch_1|onoff.switch_2|onoff.switch_3|onoff.switch_4|onoff.switch_5|onoff.switch_6",
That's not possible, because the device dynamically has 1-6 sub-switches, and dropdowns are static.

2024-07-08 10:16 UTC, bobvandevijver commented on drivers/socket/driver.flow.compose.json
> +      "$filter": "capabilities=onoff.switch_1|onoff.switch_2|onoff.switch_3|onoff.switch_4|onoff.switch_5|onoff.switch_6",
A dropdown would most certainly be possible, but has the same cluttering issue dedicated button cards have, although with a dropdown it would only be in the store and not in the Homey interface.

It would even be better if we can prevent the default flow card generation for the `onoff` capability, so all options can be combined in a single card, but as far as I know that is not possible.

Both dropdowns and dedicated cards do ensure unnecessary code duplication, which as a consequence causes a higher bug possibility.

The ideal solution would be to have the `registerArgumentAutocompleteListener` available for the dropdown cards as well, or, maybe as temporary workaround, disable the search field for the `autocomplete` card itself.

Until that is possible, the `autocomplete` as it is currently is the best compromise in terms of user usability and code maintainability.

2024-07-08 10:21 UTC, WeeJeWel commented on drivers/socket/driver.flow.compose.json
> +      "$filter": "capabilities=onoff.switch_1|onoff.switch_2|onoff.switch_3|onoff.switch_4|onoff.switch_5|onoff.switch_6",
I strongly disagree. Please use a separate card for every sub-switch. The UX is more important than 'code neatness'.

2024-07-12 11:36 UTC, merged