Add heater
athombv/com.tuya pull request #37
Opened 2024-07-06 12:16 UTC by JELoohuis

- **Added support for the heater category of devices.**
Since my test device had limited functionality the following capabilities were implemented and tested:
  - onoff (switch)
  - target_temperature (temp_set)
  - measure_temperature (temp_current)
  - measure_power (work_power)

  The eco-mode (mode_eco) and child_lock (lock) capability were added untested,
  so it would be nice to get feedback on them from users with devices that support them.

  The level instruction could not be tested and was not added,
  as it is unclear whether all devices that support it use all three levels,
  which would dictate the type of Homey capability used.

**TODO:**
- finalize icons and images
    - The child_lock capability now uses the default lock icon.
    - The eco_mode button still needs an icon.
    - The device icon is based on the heater category icon in the vector repository,
      though it may need a new icon that matches the new Homey style better.

2024-07-12 12:00 UTC, MerelHudepohl commented
@JELoohuis i'm gonna put this in test so we might get some feedback. Once the icons are available please add them.

2024-07-12 13:47 UTC, wouter-athom commented on drivers/heater/device.js
> +    }
Does the presence of 'work_power' guarantee the presence of 'cur_power'?

2024-07-12 13:47 UTC, wouter-athom commented on drivers/heater/device.js
> +  }
You used a boolean cast for the other listeners, but not for this one.

2024-07-12 13:47 UTC, wouter-athom commented on lib/TuyaOAuth2Driver.js
> +      const deviceProperties = this.onTuyaPairListDeviceProperties({...device}, deviceSpecs);
These deviceSpecs are never used. Is this for a future update?

2024-07-16 08:52 UTC, JELoohuis commented on drivers/heater/device.js
> +    }
This was a typo, fixed in 6c6b0c27802292f381c65ba86c9b73383dc6e85d

2024-07-16 08:53 UTC, JELoohuis commented on drivers/heater/device.js
> +  }
The redundant casts were removed in bf758dde21f712c84ebf1343fe1a04347f682dfa

2024-07-16 08:56 UTC, JELoohuis commented on lib/TuyaOAuth2Driver.js
> +      const deviceProperties = this.onTuyaPairListDeviceProperties({...device}, deviceSpecs);
The specifications are used to set the temperature range supported by the device in eb47c39af132eae3aee1555ae4011f54faa33590

2024-08-07 07:07 UTC, bobvandevijver requested changes

2024-08-07 07:07 UTC, bobvandevijver commented on drivers/heater/driver.flow.compose.json
> +  "triggers": []
We probably also want triggers for the child lock and eco mode capabilities, as those can be changed on the device as well.

2024-08-07 07:07 UTC, bobvandevijver commented on drivers/heater/driver.js
> +  ];
Let's always put this as the first code in the driver class, so it can be spotted easily.

2024-08-07 11:46 UTC, JELoohuis commented on drivers/heater/driver.flow.compose.json
> +  "triggers": []
Added in a95db003b642934471f0578717ba7ae2fb077a8e

2024-08-08 13:52 UTC, bobvandevijver approved these changes

2024-08-08 13:52 UTC, merged