Add camera
athombv/com.tuya pull request #39
Opened 2024-07-06 19:16 UTC by JELoohuis

- **Added support for the camera category of devices.**
    The camera device class is quite extensive, and some parts quite complex to integrate with Homey, so I stuck to those that could be readily tested with my device.
    
    Images are not yet supported due to Homey not having the correct rights in the Tuya API.
    It may be possible to decrypt the images sent in event messages, but this will require figuring out the exact encryption parameters used.
    The key for this is readily available through the Tuya API as local_key in the device details.
    
    Since the camera device class has a huge amount of capabilities,
    those that were deemed unlikely to be changed by hand often were implemented as settings.
    For those settings that may be changed semi-regularly flows were added.
    This is of course a compromise, as the settings that are not applicable cannot be disabled, unlike capabilities.
    
    The zoom control/stop and battery level are not supported by my test device, so they are untested.
    It would be nice to receive feedback on these from people with devices that do support them.

**TODO:**
- Device assets
    - device images and icons
    - capability icons
        - ptz control arrows
        - zoom control
        - custom alarms
        - siren
        - auto-patrol

2024-07-08 08:42 UTC, WeeJeWel commented
There was already a [branch for camera support](https://github.com/athombv/com.tuya/tree/feature/camera), but development has been paused because we cannot get access to the snapshot images or video streams.

Why make this PR at all, if we cannot get those?

2024-08-05 09:08 UTC, bobvandevijver commented on .homeycompose/capabilities/ptz_control_horizontal.json
> +    }
We will need to use `up`/`idle`/`down` for the ternary component so the icons will be displayed correctly (also hold for the vertical and zoom control). Value translation will need to be done in the app code.

2024-08-07 07:21 UTC, bobvandevijver requested changes

2024-08-07 12:01 UTC, JELoohuis commented on drivers/camera/driver.flow.compose.json
> +  "triggers": [
These are only ever set to true by events, and then to false by a timeout, so I don't think the false cards are very useful here. My test device did not generate multiple events within the timeout, but the cards may be useful if we want to combine events if this does happen.

2024-08-07 12:25 UTC, JELoohuis commented on drivers/camera/driver.js
> +      ) {
Fixed in 750408fd124b13de0682a5f926b66740f58c9ac6

2024-08-07 12:30 UTC, JELoohuis commented on drivers/camera/device.js
> +} = require("./driver");
Fixed in 09a9c9fcdc7b838f441a3919afbea1b155620bf1

2024-08-07 13:11 UTC, JELoohuis commented on drivers/camera/driver.flow.compose.json
> +  "triggers": [
I reworked the event handling in f30d99d79deea4a3904556bc7a68aa9f99df1adf and added the flows in ce1009080ffd531beca5bf010eab0a9b84e9e22e

2024-08-08 14:16 UTC, bobvandevijver approved these changes

2024-08-08 14:16 UTC, merged