Add dimmer
athombv/com.tuya pull request #46
Opened 2024-07-17 12:02 UTC by JELoohuis

- **Added support for the dimmer category of devices.**
  The following capabilities were implemented and tested:
  - onoff (switch_led_1, switch_led_2)
  - dim (bright_value_1, bright_value_2)

  The onoff is handled the same as in sockets, with 1 channel devices using the default capability,
  and 2 channel devices using it to turn both channels on/off, with sub-capabilities for the separate channels.

  In 2 channel devices the default dim capability is removed in favor of just sub-capabilities.

  The following settings were implemented and tested:
  - Minimum brightness (brightness_min_1, brightness_min_2)
  - Maximum brightness (brightness_max_1, brightness_max_2)
  - Bulb type (led_type_1, led_type_2)

  The work_mode instruction could not be tested and was not added.

**TODO:**
- finalize device icons and images

2024-08-07 07:30 UTC, bobvandevijver requested changes

2024-08-07 07:30 UTC, bobvandevijver commented on drivers/dimmer/device.js
> +          (brightnessStatus - scaleMin) / (scaleMax - scaleMin);
```suggestion
        const scaleMin = this.getSetting(tuyaBrightnessMin) * TUYA_PERCENTAGE_SCALING;
        const scaleMax = this.getSetting(tuyaBrightnessMax) * TUYA_PERCENTAGE_SCALING;
        const scaledValue = (brightnessStatus - scaleMin) / (scaleMax - scaleMin);
```

2024-08-07 07:30 UTC, bobvandevijver commented on drivers/dimmer/device.js
> +            .catch(this.error);
```suggestion
          triggerCard.trigger(this, {
              value: Math.round(scaledValue * 100) / 100, // Round to 2 decimals
          }).catch(this.error);
```

2024-08-07 07:30 UTC, bobvandevijver commented on drivers/dimmer/device.js
> +            : newValue,
```suggestion
        value: typeof newValue === "number"
            ? newValue * TUYA_PERCENTAGE_SCALING
            : newValue,
```

2024-08-07 07:30 UTC, bobvandevijver commented on drivers/dimmer/device.js
> +        this.homey.__("settings_unsupported") + " ";
```suggestion
      let unsupportedSettingsMessage = this.homey.__("settings_unsupported") + " ";
```

2024-08-07 07:30 UTC, bobvandevijver commented on drivers/dimmer/device.js
> +        this.homey.__("setting_values_unsupported") + " ";
```suggestion
      let unsupportedValuesMessage = this.homey.__("setting_values_unsupported") + " ";
```

2024-08-07 07:30 UTC, bobvandevijver commented on drivers/dimmer/device.js
> +      TUYA_PERCENTAGE_SCALING;
```suggestion
    const scaleMin = this.getSetting(`brightness_min_${subSwitch}`) * TUYA_PERCENTAGE_SCALING;
    const scaleMax = this.getSetting(`brightness_max_${subSwitch}`) * TUYA_PERCENTAGE_SCALING;
```

2024-08-07 07:30 UTC, bobvandevijver commented on drivers/dimmer/driver.js
> +  ];
Let's put this on top

2024-08-07 07:30 UTC, bobvandevijver commented on drivers/dimmer/device.js
> +const { DIMMER_SETTING_LABELS } = require("./driver");
Let's create a dedicated file for this

2024-08-07 07:30 UTC, bobvandevijver commented on drivers/dimmer/driver.js
> +      TuyaOAuth2DriverDimmer.SIMPLE_DIMMER_CAPABILITIES;
```suggestion
    const simpleCapabilities = TuyaOAuth2DriverDimmer.SIMPLE_DIMMER_CAPABILITIES;
```

2024-08-07 07:30 UTC, bobvandevijver commented on drivers/dimmer/driver.js
> +      }
```suggestion
      if (tuyaCapability === "bright_value_1") {
        props.settings["brightness_min_1"] = values.min / TUYA_PERCENTAGE_SCALING;
        props.settings["brightness_max_1"] = values.max / TUYA_PERCENTAGE_SCALING;
      }

      if (tuyaCapability === "bright_value_2") {
        props.settings["brightness_min_2"] = values.min / TUYA_PERCENTAGE_SCALING;
        props.settings["brightness_max_2"] = values.max / TUYA_PERCENTAGE_SCALING;
      }
```

2024-08-07 09:49 UTC, JELoohuis commented on drivers/dimmer/device.js
> +const { DIMMER_SETTING_LABELS } = require("./driver");
Fixed in 6198a246d7072d6eeb71dad258c68a37ab5fa07b

2024-08-08 11:19 UTC, bobvandevijver approved these changes

2024-08-08 11:38 UTC, merged