Expand lights
athombv/com.tuya pull request #67
Opened 2024-07-23 13:34 UTC by JELoohuis

**- Added support for motion lights**
The following capabilities were implemented and tested:
motion_alarm (pir_state)

The following settings were implemented and tested:
Motion Detection (switch_pir)
Motion Sensitivity (pir_sensitivity)
Motion Delay (pir_delay)
Luminance Detection: (cds)
Standby Light (standby_on)
Standby Time (standby_time)
Standby Brightness (standby_bright)

The test device did not have "standby_on", but emulated it by setting standby_bright to 0.
This is mimicked by the "Standby Light" setting when "standby_on" is not present.

**- Fixed light data ranges**
Some devices do not report their ranges. Since all categories, except for "dj", use the same values,
defaults were added based on the Tuya documentation.

**- Fixed missing dim support**
Lights that do not support either color or temperature were expected to only use "bright_value_v2" for dimming.
Now both "bright_value" and "bright_value_v2" are supported, depending on what the device reports.

2024-07-24 10:47 UTC, bobvandevijver requested changes

2024-07-24 10:47 UTC, bobvandevijver commented on drivers/light/driver.settings.compose.json
> +              "en": "Now"
What does this do? Use the current brightness as trigger?

2024-07-24 10:47 UTC, bobvandevijver commented on drivers/light/driver.settings.compose.json
> +        "type": "dropdown",
Wouldn't a number input be a better fit?

2024-07-24 10:47 UTC, bobvandevijver commented on drivers/light/driver.flow.compose.json
> +  "triggers": []
```suggestion
```

2024-07-24 10:47 UTC, bobvandevijver commented on drivers/light/driver.flow.compose.json
> +      "id": "light_standby_on",
There is no filter for this card, does every light support this? Otherwise a hint explaining that would be nice to have here.

2024-07-24 10:47 UTC, bobvandevijver commented on lib/TuyaOAuth2DeviceLight.js
> +    }
```suggestion
    if (status['pir_state'] !== undefined && this.hasCapability('alarm_motion')) {
      const pirTurnedOn = status['switch_pir'] || !this.store.tuya_capabilities.includes('switch_pir');
      const newPirState = status['pir_state'] === 'pir' && pirTurnedOn;
      this.setCapabilityValue('alarm_motion', newPirState).catch(this.error)
    }
```

2024-07-24 10:47 UTC, bobvandevijver commented on lib/TuyaOAuth2DeviceLight.js
> +          continue;
```suggestion
          // Standby setting has already been updated, so skip this one changed key
          continue;
```

2024-07-24 10:47 UTC, bobvandevijver commented on lib/TuyaOAuth2DeviceLight.js
> +      messages.push(unsupportedSettingsMessage);
```suggestion
      const mappedSettingNames = unsupportedSettings.map(
        (settingKey) => LIGHT_SETTING_LABELS[settingKey],
      );
      messages.push(this.homey.__("settings_unsupported") + " " + mappedSettingNames.join(", "));
```

2024-07-24 10:47 UTC, bobvandevijver commented on lib/TuyaOAuth2DeviceLight.js
> +      messages.push(unsupportedValuesMessage);
```suggestion
      const mappedSettingNames = unsupportedValues.map(
        (settingKey) => LIGHT_SETTING_LABELS[settingKey],
      );
      messages.push(this.homey.__("setting_values_unsupported") + " " + mappedSettingNames.join(", "));
```

2024-07-24 10:47 UTC, bobvandevijver commented on lib/TuyaOAuth2DeviceLight.js
> +      return messages.join("\n");
This does leave the UI in an inconsistent state, as unsupported settings and values will be acknowledged and stored as saved in Homey. Not necessarily an issue with unsupported settings as those won't work anyway, but with an unsupported value while others values do work it is an issue. Maybe we can revert only that particular setting?

2024-07-24 10:47 UTC, bobvandevijver commented on lib/TuyaOAuth2DriverLight.js
> +const TUYA_PERCENTAGE_SCALING = 10;
This needs to be upgraded to a constant, it is defined in the device as well.

2024-07-24 10:47 UTC, bobvandevijver commented on lib/TuyaOAuth2DriverLight.js
> +  }
I'd like to see these in a dedicated file as exported consts, so the driver doesn't need to be included by the device.

2024-07-24 10:47 UTC, bobvandevijver commented on lib/TuyaOAuth2DriverLight.js
> +    for (const status of device.status) {
This should be combined with the code above, so we do not loop `device.status` at multiple places.

How about mapping status =>code array, and using that with `.includes`?

2024-07-31 12:12 UTC, JELoohuis commented on drivers/light/driver.settings.compose.json
> +              "en": "Now"
This is not clearly defined in [the documentation](https://developer.tuya.com/en/docs/iot/motion-sensor-light?id=Kaof8blqt9w7q), but I also expect that behavior.

2024-07-31 12:49 UTC, JELoohuis commented on lib/TuyaOAuth2DeviceLight.js
> +      return messages.join("\n");
The Homey settings are kept in sync with the Tuya device state, so this should not be any more of an issue than the usual UI inconsistency.

2024-07-31 13:25 UTC, JELoohuis commented on lib/TuyaOAuth2DriverLight.js
> +    for (const status of device.status) {
Refactored in 78ae335fc962530832bcd04bbe5e6ee61d71bfdc

2024-07-31 13:26 UTC, JELoohuis commented on lib/TuyaOAuth2DriverLight.js
> +  }
Refactored in cce9b2b7b3f951120fb0e1b7d2a9b4816eac5a79

2024-07-31 13:26 UTC, JELoohuis commented on lib/TuyaOAuth2DriverLight.js
> +const TUYA_PERCENTAGE_SCALING = 10;
Refactored in cce9b2b7b3f951120fb0e1b7d2a9b4816eac5a79

2024-07-31 13:27 UTC, JELoohuis commented on lib/TuyaOAuth2DeviceLight.js
> +      messages.push(unsupportedValuesMessage);
Fixed in cf8bf409b2889688983f671bba3358a6615c0e5a

2024-07-31 13:28 UTC, JELoohuis commented on drivers/light/driver.flow.compose.json
> +  "triggers": []
Fixed in cf8bf409b2889688983f671bba3358a6615c0e5a

2024-07-31 13:28 UTC, JELoohuis commented on drivers/light/driver.flow.compose.json
> +      "id": "light_standby_on",
Fixed in cf8bf409b2889688983f671bba3358a6615c0e5a

2024-07-31 13:28 UTC, JELoohuis commented on lib/TuyaOAuth2DeviceLight.js
> +    }
Fixed in cf8bf409b2889688983f671bba3358a6615c0e5a

2024-07-31 13:28 UTC, JELoohuis commented on lib/TuyaOAuth2DeviceLight.js
> +          continue;
Fixed in cf8bf409b2889688983f671bba3358a6615c0e5a

2024-07-31 13:28 UTC, JELoohuis commented on lib/TuyaOAuth2DeviceLight.js
> +      messages.push(unsupportedSettingsMessage);
Fixed in cf8bf409b2889688983f671bba3358a6615c0e5a

2024-07-31 13:40 UTC, bobvandevijver approved these changes

2024-08-01 14:41 UTC, merged