update tags
athombv/com.tuya pull request #70
Opened 2024-07-24 20:16 UTC by vierlijner

Udate list of brands for search tags

2024-07-25 07:17 UTC, bobvandevijver commented
This actually needs to be adjusted in the `.homeycompose/app.json` file, from which the `app.json` is being generated. Can you also move the brands on the top in the correct alphabetical order, except for Tuya, Tuya Smart and Smart Life?

2024-07-25 07:32 UTC, bobvandevijver requested changes
This actually needs to be adjusted in the .homeycompose/app.json file, from which the app.json is being generated. So both files need an update.

2024-08-02 07:22 UTC, vierlijner commented
Done

2024-08-02 09:04 UTC, bobvandevijver commented on .homeycompose/app.json
> +      "Hema",
```suggestion
```

2024-08-02 09:04 UTC, bobvandevijver commented on app.json
> +      "Hema",
```suggestion
```

2024-08-02 09:05 UTC, bobvandevijver approved these changes

2024-08-02 09:06 UTC, merged

2024-08-02 09:06 UTC, bobvandevijver commented
@vierlijner thanks!