Improve unknown device functionality
athombv/com.tuya pull request #96
Opened 2024-07-30 12:18 UTC by JELoohuis

**Added 'other' devices to webhook registration**
A separate register of 'other' devices is kept, so that devices with dedicated drivers can also be added as 'other' without breaking them.

**Added flow cards for receiving Tuya statuses**
These trigger flow cards match the existing action flows, supporting numbers, booleans, strings and JSON.
Since Tuya sometimes encodes JSON twice strings are also checked for JSON format, with the action card updated to do the same.

TODO:
- add support for Tuya automation scenes

2024-07-30 13:53 UTC, bobvandevijver requested changes

2024-07-30 13:53 UTC, bobvandevijver commented on .homeycompose/flow/triggers/receive_status_boolean.json
> +    },
I wonder why we are filtering on the device class: every Tuya device should have these flowcards, isn't that correct? If not, why is the doorbell different?

2024-07-30 13:53 UTC, bobvandevijver commented on lib/TuyaOAuth2App.js
> +"use strict";
Quotes have been changed while they shouldn't. At least not in the scope of this PR.

2024-07-30 13:53 UTC, bobvandevijver commented on lib/TuyaOAuth2App.js
> +        })
```suggestion
        .filter(({ code }) => code.toLowerCase().includes(query.toLowerCase()))
```

2024-07-30 13:53 UTC, bobvandevijver commented on lib/TuyaOAuth2App.js
> +      .registerRunListener(async (args) => sendCommandRunListener(args))
```suggestion
      .registerRunListener(sendCommandRunListener)
```

I do not believe the additional function wrapper is necessary here.

2024-07-30 13:53 UTC, bobvandevijver commented on lib/TuyaOAuth2App.js
> +        }),
```suggestion
        generalControlAutocompleteListener(query, args, ({ value }) =>
          typeof value === "string" && !TuyaOAuth2Util.hasJsonStructure(value)
        ),
```

2024-07-30 13:53 UTC, bobvandevijver commented on lib/TuyaOAuth2App.js
> +        }),
```suggestion
        generalControlAutocompleteListener(query, args, ({ value }) => typeof value === "number"),
```

2024-07-30 13:53 UTC, bobvandevijver commented on lib/TuyaOAuth2App.js
> +        }),
```suggestion
        generalControlAutocompleteListener(query, args, ({ value }) => typeof value === "boolean"),
```

2024-07-30 13:53 UTC, bobvandevijver commented on lib/TuyaOAuth2App.js
> +        }),
```suggestion
        generalControlAutocompleteListener(query, args, ({ value }) =>
          typeof value === "object" || TuyaOAuth2Util.hasJsonStructure(value)
        ),
```

2024-07-30 13:53 UTC, bobvandevijver commented on lib/TuyaOAuth2App.js
> +        }),
Can you also adjust the other single line function so we do not need to {return} part?

2024-07-30 13:53 UTC, bobvandevijver commented on lib/TuyaOAuth2Client.js
> +                    }
```suggestion
                      await registeredDevice?.onStatus(message.body.data.deviceStatus);
```

Not sure if this works well together with await, but it looks a lot nicer (or it this Typescript only perhaps?).

2024-07-30 13:53 UTC, bobvandevijver commented on lib/TuyaOAuth2Device.js
> +
```suggestion
      let triggerCardId;
```

2024-07-30 13:53 UTC, bobvandevijver commented on lib/TuyaOAuth2Device.js
> +      }).catch(err => this.error(err))
```suggestion
      }).catch(this.error)
```

2024-07-31 10:09 UTC, JELoohuis commented on lib/TuyaOAuth2App.js
> +"use strict";
Fixed in 65d3d2302e743d0a040d09b0b9127d0be570990b

2024-07-31 10:09 UTC, JELoohuis commented on lib/TuyaOAuth2App.js
> +        })
Fixed in 65d3d2302e743d0a040d09b0b9127d0be570990b

2024-07-31 10:11 UTC, JELoohuis commented on lib/TuyaOAuth2App.js
> +        }),
Fixed in 65d3d2302e743d0a040d09b0b9127d0be570990b

2024-07-31 10:14 UTC, JELoohuis commented on lib/TuyaOAuth2App.js
> +        }),
Fixed in 65d3d2302e743d0a040d09b0b9127d0be570990b

2024-07-31 10:15 UTC, JELoohuis commented on lib/TuyaOAuth2App.js
> +        }),
Fixed in 65d3d2302e743d0a040d09b0b9127d0be570990b

2024-07-31 10:29 UTC, JELoohuis commented on lib/TuyaOAuth2Client.js
> +                    }
As discussed in person, the optional chaining is easier to miss than the if-statement, so they will remain unchanged.

2024-07-31 10:38 UTC, JELoohuis commented on lib/TuyaOAuth2App.js
> +      .registerRunListener(async (args) => sendCommandRunListener(args))
Fixed in 6619eccc011049297b03d5f28ade46174224074c

2024-07-31 10:38 UTC, JELoohuis commented on lib/TuyaOAuth2Device.js
> +
Fixed in 6619eccc011049297b03d5f28ade46174224074c

2024-07-31 10:38 UTC, JELoohuis commented on lib/TuyaOAuth2Device.js
> +      }).catch(err => this.error(err))
Fixed in 6619eccc011049297b03d5f28ade46174224074c

2024-07-31 10:40 UTC, JELoohuis commented on lib/TuyaOAuth2App.js
> +        }),
Fixed in 65d3d2302e743d0a040d09b0b9127d0be570990b

2024-07-31 11:13 UTC, bobvandevijver approved these changes

2024-07-31 11:14 UTC, merged

2024-08-09 10:05 UTC, mruiter commented
The function kinda works . The auto fill of the values is missing a lot of available values.
And since i can only select the values that came back in the app and my own values that i know that get reported since they work great in the community app it's still not functioning like it should.

The Athom tuya app gives me 12 different values combined with the text bool number etc

The community app gives me 39 ! values to read from
Thats a big difference , most of the important values are missing